name: Daily Readme Update

on:
  schedule:
    - cron: "0 4,8,12,17,22 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or specify the version your project requires

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          npm run dev
          git config --global user.email "ujjwalsaini0007+workflow@gmail.com"
          git config --global user.name "Ujjwal"
          git add README.md
          git commit -m "Updated README on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
          git push origin main
