name: Daily Readme Update

on:
  schedule:
    - cron: "0 4,8,12,16,17,18,19,20,21,22,23 * * *" # Scheduled to run at specified times

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version to use

      - name: Install Dependencies
        run: |
          cd ActionWorkflow_Integration
          npm install

      - name: Run Script
        run: |
          cd ActionWorkflow_Integration
          npm run dev
          git config --global user.email "ujjwalsaini0007+workflow@gmail.com"
          git config --global user.name "Ujjwal"
          git add README.md
          git commit -m "Updated README on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
          git push origin main
