name: Daily Readme Update

on:
  schedule:
    - cron: "*/10 4,8,12,16,17,18,19,20,21,22,23 * * *" # Run every 10 minutes during specified hours.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Script and Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dev
          git config user.email "ujjwalsaini0007+workflow@gmail.com"
          git config user.name "UjjwalSaini07"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Auto Updated README on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
            git push origin main
          else
            echo "No changes to commit."
          fi
