name: Daily Readme Update

on:
  schedule:
    - cron: "0 4,8,12,17,19,22 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Script
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          git config --global user.email "ujjwalsaini0007+workflow@gmail.com"
          git config --global user.name "Ujjwal"
          git add README.md
          git commit -m "Updated README on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
          git push origin main
